[tool.poetry]
name = "streamlit-alpha"
version = "0.1.0"
description = ""
authors = ["rookie <juan.diegoam@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
